# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.10
    hooks:
      - id: ruff
      - id: ruff-format
  - repo: https://github.com/python-poetry/poetry
    rev: "1.8.3"
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
        args:
          ["-f", "requirements.txt", "-o", "requirements.txt", "--with", "api"]
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
